import { Header } from '@/components/header'
import { Footer } from '@/components/footer'

export default function TermsOfService() {
  return (
    <>
      <Header />
      <main className="min-h-screen bg-background py-20">
        <div className="max-w-4xl mx-auto px-4">
          <h1 className="text-4xl font-black mb-8 tracking-tight">TERMS OF SERVICE</h1>
          <div className="prose prose-invert max-w-none space-y-8 text-muted-foreground">
            <section>
              <h2 className="text-xl font-bold text-foreground">1. Acceptance of Terms</h2>
              <p>
                By accessing or using the O2-5 Prediction Platform (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">2. Description of Service</h2>
              <p>
                O2-5 provides football match analysis, statistics, and algorithm-generated predictions. These predictions are for informational and entertainment purposes only. We do not offer gambling or betting services.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">3. No Financial Advice / No Guarantee</h2>
              <p>
                The predictions generated by our AI algorithm are based on historical data and statistical models. They do not guarantee future results. Betting on sports involves significant risk. O2-5 is not responsible for any financial losses incurred based on the information provided by the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">4. User Conduct</h2>
              <p>
                Users agree not to use the Service for any unlawful purpose. You may not scrape, copy, or redistribute our proprietary predictions without explicit written permission.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">5. Intellectual Property</h2>
              <p>
                All content, including our prediction algorithms, UI design, and logos, are the property of O2-5 and are protected by international copyright and trademark laws.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">6. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, O2-5 shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground">7. Changes to Terms</h2>
              <p>
                We reserve the right to modify these terms at any time. Your continued use of the Service after changes are posted constitutes your acceptance of the new terms.
              </p>
            </section>
            
            <p className="text-xs italic pt-8 border-t border-border">
              Last updated: April 25, 2026
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}
